on: push
jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Run tests
        run: |
          pip install .
          python -m tests
      - name: Run type checks
        run: |
          pip install mypy
          mypy compare50 --ignore-missing-imports
